{{- if .Values.concourse.web.postgres.operator.enabled -}}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ template "concourse.postgresql.fullname" . }}
  labels:
    app: {{ template "concourse.web.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  teamId: "concourse"
  volume:
    size: {{ .Values.concourse.web.postgres.operator.volumeSize }}
    storageClass: {{ .Values.concourse.web.postgres.operator.storageClass }}
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  numberOfInstances: 2
  {{- if .Values.concourse.web.postgres.operator.resources }}
  resources: {{- toYaml .Values.concourse.web.postgres.operator.resources | nindent 4 }}
  {{- end }}
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
      - hostssl all all 0.0.0.0/0 md5
      - host    all all 0.0.0.0/0 md5
    maximum_lag_on_failover: 0
    synchronous_mode: true
    synchronous_mode_strict: true
  users:
    concourse:
      - superuser
      - createdb
  databases:
    concourse: concourse
  postgresql:
    version: "11"
{{- if .Values.concourse.web.postgres.operator.serviceMonitor.enabled }}
  sidecars:
    - name: "prometheus-exporter"
      image: "wrouesnel/postgres_exporter:v0.8.0"
      ports:
        - name: exporter
          containerPort: 9187
          protocol: TCP
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 500m
          memory: 100Mi
      env:
        - name: "DATA_SOURCE_URI"
          value: "{{ template "concourse.postgresql.fullname" . }}?sslmode=disable"
        - name: "DATA_SOURCE_USER"
          valueFrom:
            secretKeyRef:
              name: postgres.{{ template "concourse.postgresql.fullname" . }}.credentials
              key: username
        - name: "DATA_SOURCE_PASS"
          valueFrom:
            secretKeyRef:
              name: postgres.{{ template "concourse.postgresql.fullname" . }}.credentials
              key: password
        - name: "PG_EXPORTER_AUTO_DISCOVER_DATABASES"
          value: "true"
{{- end -}}
{{- end -}}
